### ISSUE TITLE
Stopped working after recent Alfred update

### ISSUE THREAD

**Issue by jasonlung** [mpco/AlfredWorkflow-Calibre-Search#6]
Hello developer, this great workflow stopped working after recent Alfred update, not sure about the exact sub-version, though. Could you please fix it? Thank you very much.

**Comment by clang13** [comment]
It's likely due to the removal of Python 2 from macOS, which requires workflows that use Python 2 to be upgraded to use Python 3 or patched to look for Python 2 somewhere else.

You can find patched versions of several workflows (including this one) at: https://github.com/alfredapp/updated-third-party-python2-workflows#workflows. Note the instructions you'll need to run to install Python 2. I've downloaded the patched version and it appears to work as expected.

**Comment by jasonlung** [comment]
Hi Lang, thanks for helping out, I tried reinstalling Python 2, reboot, reinstall calibre-search workflow, the workflow still didn't work on my end with Alfred 4 and Alfred 5 Early Access(thought you might want to know it), will try on a new mac this fall and see how it goes. Take care.

**Comment by jasonlung** [comment]
Hello dev, problem solved. Thank you so much.
